### ISSUE TITLE
beta38 and above crash on world load due to NoSuchMethodError from HoloInventory

### ISSUE THREAD

**Issue by rinOfTheStars** [GTNewHorizons/Angelica#947]
### Your GTNH Discord Username

rinofthestars

### Mod Version

1.0.0-beta38 (also occurs on beta39, beta40, and beta41) 

### Bug Report

Running the game on a M1-gen Apple Silicon Mac Mini under macOS. Seems to be entirely new bug, not a regression of the one fixed in #891? `1.0.0-beta37` works fine, so it _is_ a regression of some sort, though. Crash report, `fml-client-latest.log`, and `latest.log` can be found [here.](https://gist.github.com/rinOfTheStars/f3530a354cb5e85482365c8e23996658)

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Shaders

No

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

GTNH 2.7.4 stable for Java 21, w/ the following changes:
- Angelica upgraded to `1.0.0-beta38` (or above)
- NEI upgraded to `2.7.40-GTNH`
- GTNHLib upgraded to `0.6.21`
- Unimixins upgraded to `0.1.20`

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [x] I have read the known incompatibilities and this is not related to one of those.
- [x] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by Caedis** [comment]
You updated other 4 mods, but didnt also update HoloInventory  

https://github.com/GTNewHorizons/HoloInventory/releases/download/2.5.1-GTNH/holoinventory-2.5.1-GTNH.jar

**Comment by rinOfTheStars** [comment]
I'll see if the HoloInv update works later today. If it does, that should probably be added as an incompatibility to the README for Angelica so others can avoid this issue.

**Comment by rinOfTheStars** [comment]
Updated HoloInv does fix the issue. I'm going to close the issue now, but this incompatibility should be _really_ added to the README.
