### ISSUE TITLE
Vanilla chests flicker when Logistics Pipes are in view and GL state caching is enabled

### ISSUE THREAD

**Issue by szuend** [GTNewHorizons/Angelica#501]
### Your GTNH Discord Username

nimodota

### Mod Version

1.0.0-alpha50

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

This looks very similar to GTNewHorizons/GT-New-Horizons-Modpack#16233 but filed with more concrete repro steps.

1. Create a new standard flat world.
2. Place some vanilla chests
3. Place any "Logistics Pipes" Pipe, e.g. an "Unrouted Transport Pipe"

Observe that the chests render with wrong brightness.

![broken](https://github.com/GTNewHorizons/Angelica/assets/325588/80ae8862-a708-46e8-a361-96be4d8de908)
![working](https://github.com/GTNewHorizons/Angelica/assets/325588/87c7cf7c-fc8c-4460-a819-91b784e23ba1)

Observe that every time you move the pipe out of the viewport the chests switch back to bright. As soon as the pipe comes back into view the chests switch back to darker.

The chest's brightness is also fixed by disabling the GL state caching.

### Mod List or GTNH Pack Version

Logistics Pipe Version: 1.2.1-GTNH

Running from a Logistics Pipes checkout via `gradlew :runClient21` + manually added angelica mod in the run directory.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by szuend** [comment]
To capture some of the discord discussion: The current suspicion is that the LP pipe [TESR](https://github.com/GTNewHorizons/LogisticsPipes/blob/b05340a7472587196b3771652db77140c99b6f8f/src/main/java/logisticspipes/renderer/newpipe/LogisticsNewRenderPipe.java#L718) sets some state in the display list that Angelica doesn't properly replay.

Note that `LogisticsNewRenderPipe` does not implement the TESR interface, but the actual TESR delegates to the `LogisticsNewRenderPipe`.

**Comment by Atadele** [comment]
I have this problem too, but it happened when I updated to 2.6.1 and instead of logistics pipes its Jabba barrels with items in them. https://youtu.be/WCC7y0EoGSE

**Comment by Cleptomania** [comment]
This has been fixed in Logistics Pipes
