### ISSUE TITLE
Crash with custom npcs dbc addon

### ISSUE THREAD

**Issue by reuben-matus** [GTNewHorizons/Angelica#1163]
### Your GTNH Discord Username

reuben9701

### Mod Version

1.0.0-beta75-pre

### Bug Report

I get 
Caught exception from npcdbc
java.lang.NoSuchMethodError: com.gtnewhorizons.angelica.glsm.GLStateManager.glDrawBuffers(I)V 
when trying to run angelica with the mod mentioned above in the title, it gets through a few loading screens on the gui but then crashes

here is the log file:
[fml-client-latest.log](https://github.com/user-attachments/files/24009549/fml-client-latest.log)

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Shaders

No

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

Mods:
  [✔] +unimixins-all-1.7.10-0.1.23
  [✔] angelica-1.0.0-beta75-pre
  [✔] CustomNPC-Plus-1.10.2
  [✔] DragonBlockC-v1.4.85
  [✔] gtnhlib-0.8.21
  [✔] JBRA-Client-v1.6.52
  [✔] JRMCore-v1.3.51
  [✔] npcdbc-1.1.3

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [x] I have read the known incompatibilities and this is not related to one of those.
- [x] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by DarkShadow44** [comment]
This is caused by 33de1de9c4d463b77bfb30ee026397d9c5f3ebba

**Comment by reuben-matus** [comment]
fixed with 1.0.0-beta77-pre
